### ISSUE TITLE
Error de entrada

### ISSUE THREAD

**Issue by przdavid** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-hipema#1]
En esta línea sería necesario poner un input.

https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-hipema/blob/1e82800b720f442cefc57f149a0e18d74705a41f/ej01nombre_saluda.py#L16

**Comment by hipema** [comment]
Debería quedar así?


nombre=input("Introduce tu nombre: ")

**Comment by przdavid** [comment]
Exacto.

**Comment by jaimerabasco** [comment]
Falta asignarte el commit y aplicar labels y milestone @hipema 
Cierralo después
