### ISSUE TITLE
Uso de try

### ISSUE THREAD

**Issue by przdavid** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-hipema#2]
En clase nos recomendaron no usar try hasta haber visto las excepciones.

https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-hipema/blob/208de5d42e8f963244c5df1baebb014aa5bd8bef/ej20monedero.py#L33

**Comment by hipema** [comment]
En este caso, como era un ejercicio sencillo y Rafa había puesto anteriormente un ejemplo muy similar, el uso de las excepciones parece bastante fácil, no resulta complejo y hacer que el programa no termine de forma abrupta.
